#! /usr/bin/env python2
"""
export trac tickets to GitHub issues
"""
from argparse import ArgumentParser

from trac2.convert import convert_text
from trac2.github import GitHubAdaptor
from trac2.trac import TracAdaptor


def parse_config(filename):
    """
    a config reader
    """
    config = dict()

    execfile(filename, dict(), config)

    return config


def main():
    """
    entry point
    """
    parser = ArgumentParser(description=__doc__)

    parser.add_argument('--dry-run', action='store_true',
                        help='do not perform any modifications')
    parser.add_argument('config', metavar='FILE',
                        help='configuration file for the migration')

    args = parser.parse_args()

    config = parse_config(args.config)

    github = GitHubAdaptor(config['github'], args.dry_run)

    for ticket in TracAdaptor(config['trac'], args.dry_run).get_tickets():
        data = ticket.as_dict()
        data['description'] = convert_text(data['description'])

        issue, url = github.create_issue(data)

        ticket.mark_exported(issue, url)


if __name__ == '__main__':
    main()
